export const NikeData = [
    {
      id: 1,
      mainImg: "./images/NIKE/Nike1_1.png",
      extraImgList: [
        "./images/NIKE/Nike1_1.png",
        "./images/NIKE/Nike1_2.png",
        "./images/NIKE/Nike1_3.png",
      ],
      name: "ROSHE TWO BLACK",
      brandName: "NIKE",
      code: "844931-002",
      price: "1.450.000 VND",
      new: "New",
      discount: "20%",
      sizes: [37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 2,
      mainImg: "./images/NIKE/Nike2_1.png",
      extraImgList: [
        "./images/NIKE/Nike2_1.png",
        "./images/NIKE/Nike2_2.png",
        "./images/NIKE/Nike2_3.png",
      ],
      name: "AIR PRESTO ULTRA BRIGHT CRIMSON",
      brandName: "NIKE",
      code: "835738-800",
      price: "1.490.000 VND",
      discount: "13%",
      sizes: [36, 36.5, 37, 38, 38.5, 39, 40],
    },
    {
      id: 3,
      mainImg: "./images/NIKE/Nike3_1.png",
      extraImgList: [
        "./images/NIKE/Nike3_1.png",
        "./images/NIKE/Nike3_2.png",
        "./images/NIKE/Nike3_3.png",
      ],
      name: "COURT VISION LOW TRIPLE WHITE",
      brandName: "NIKE",
      code: "CD5434-100",
      price: "1.900.000 VND",
      discount: "9%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 4,
      mainImg: "./images/NIKE/Nike4_1.png",
      extraImgList: [
        "./images/NIKE/Nike4_1.png",
        "./images/NIKE/Nike4_2.png",
        "./images/NIKE/Nike4_3.png",
      ],
      name: "RUNNING REACT ELEMENT 87",
      brandName: "NIKE",
      code: "AQ1090-002",
      price: "1.590.000 VND",
      discount: "11%",
      sizes: [39, 40],
    },
    {
      id: 5,
      mainImg: "./images/NIKE/Nike5_1.png",
      extraImgList: [
        "./images/NIKE/Nike5_1.png",
        "./images/NIKE/Nike5_2.png",
        "./images/NIKE/Nike5_3.png",
      ],
      name: "CORTEZ BASIC GS",
      brandName: "NIKE",
      code: "BV0014-100",
      price: "2.350.000 VND",
      discount: "15%",
      sizes: [37, 37.5, 38],
    },
    {
      id: 6,
      mainImg: "./images/NIKE/Nike6_1.png",
      extraImgList: [
        "./images/NIKE/Nike6_1.png",
        "./images/NIKE/Nike6_2.png",
        "./images/NIKE/Nike6_3.png",
      ],
      name: "COURT VISION ALTA TXT LIGHT SOFT PINK MAGIC EMBER",
      brandName: "NIKE",
      code: "CW6536-101",
      price: "1.950.000 VND",
      discount: "12.5%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 7,
      mainImg: "./images/NIKE/Nike7_1.png",
      extraImgList: [
        "./images/NIKE/Nike7_1.png",
        "./images/NIKE/Nike7_2.png",
        "./images/NIKE/Nike7_3.png",
      ],
      name: "AIR FORCE 1 SHADOW 8 BIT BLACK",
      brandName: "NIKE",
      code: "CV8480-001",
      price: "2.790.000 VND",
      discount: "8%",
      sizes: [36.5, 37, 37.5, 38, 38.5],
    },
    {
      id: 8,
      mainImg: "./images/NIKE/Nike8_1.png",
      extraImgList: [
        "./images/NIKE/Nike8_1.png",
        "./images/NIKE/Nike8_2.png",
        "./images/NIKE/Nike8_3.png",
      ],
      name: "DROP TYPE HBR WHITE DEEP ROYAL BLUE",
      brandName: "NIKE",
      code: "CQ0989-100",
      price: "1.290.000 VND",
      discount: "11%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38],
    },
    {
      id: 9,
      mainImg: "./images/NIKE/Nike9_1.png",
      extraImgList: [
        "./images/NIKE/Nike9_1.png",
        "./images/NIKE/Nike9_2.png",
        "./images/NIKE/Nike9_3.png",
      ],
      name: "ROSHE ONE WHITE",
      brandName: "NIKE",
      code: "511881-112",
      price: "2.290.000 VND",
      discount: "13%",
      new: "New",
      sizes: [37.5, 38, 38.5, 39, 40],
    },
    {
      id: 10,
      mainImg: "./images/NIKE/Nike10_1.png",
      extraImgList: [
        "./images/NIKE/Nike10_1.png",
        "./images/NIKE/Nike10_2.png",
        "./images/NIKE/Nike10_3.png",
      ],
      name: "JOYRIDE RUN CC",
      brandName: "NIKE",
      code: "AO1742-003",
      price: "1.650.000 VND",
      discount: "13%",
      sizes: [37.5, 38, 38.5, 39, 40],
    },
    {
      id: 11,
      mainImg: "./images/NIKE/Nike11_1.png",
      extraImgList: [
        "./images/NIKE/Nike11_1.png",
        "./images/NIKE/Nike11_2.png",
        "./images/NIKE/Nike11_3.png",
      ],
      name: "COURT VISION LOW HOLOGRAM",
      brandName: "NIKE",
      code: "CW5596-100",
      price: "1.900.000 VND",
      discount: "13%",
      new: "New",
      sizes: [35.5, 36, 36.5, 38, 38.5, 39, 40],
    },
    {
      id: 12,
      mainImg: "./images/NIKE/Nike12_1.png",
      extraImgList: [
        "./images/NIKE/Nike12_1.png",
        "./images/NIKE/Nike12_2.png",
        "./images/NIKE/Nike12_3.png",
      ],
      name: "DUNK HIGH UP VARSITY MAIZE",
      brandName: "NIKE",
      code: "DH3718-001",
      price: "2.490.000 VND",
      discount: "13%",
      new: "New",
      sizes: [36.5, 37, 37.5, 38, 38.5, 39],
    },
  ];
  
  export const JordanData = [
    {
      id: 1,
      mainImg: "./images/JORDAN/Jordan1_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan1_1.png",
        "./images/JORDAN/Jordan1_2.png",
        "./images/JORDAN/Jordan1_3.png",
      ],
      name: "AIR JORDAN 1 LOW BULLS",
      brandName: "JORDAN",
      code: "553558-163",
      price: "4.900.000 VND",
      new: "New",
      discount: "13%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 2,
      mainImg: "./images/JORDAN/Jordan2_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan2_1.png",
        "./images/JORDAN/Jordan2_2.png",
        "./images/JORDAN/Jordan2_3.png",
      ],
      name: "AIR JORDAN 1 ELEVATE LOW ONYX",
      brandName: "JORDAN",
      code: "DH7004-102",
      price: "4.800.000 VND",
      discount: "15%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 3,
      mainImg: "./images/JORDAN/Jordan3_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan3_1.png",
        "./images/JORDAN/Jordan3_2.png",
        "./images/JORDAN/Jordan3_3.png",
      ],
      name: "AIR JORDAN 1 HIGH OG HAND CRAFTED",
      brandName: "JORDAN",
      code: "DH3097-001",
      price: "5.900.000 VND",
      discount: "18%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 4,
      mainImg: "./images/JORDAN/Jordan4_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan4_1.png",
        "./images/JORDAN/Jordan4_2.png",
        "./images/JORDAN/Jordan4_3.png",
      ],
      name: "AIR JORDAN 1 ZOOM HIGH SISTERHOOD",
      brandName: "JORDAN",
      code: "CZ1360-401",
      price: "4.400.000 VND",
      discount: "11%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 5,
      mainImg: "./images/JORDAN/Jordan5_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan5_1.png",
        "./images/JORDAN/Jordan5_2.png",
        "./images/JORDAN/Jordan5_3.png",
      ],
      name: "AIR JORDAN 4 X OFF-WHITE SAIL",
      brandName: "JORDAN",
      code: "CV9388-100",
      price: "28.900.000 VND",
      discount: "13%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 6,
      mainImg: "./images/JORDAN/Jordan6_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan6_1.png",
        "./images/JORDAN/Jordan6_2.png",
        "./images/JORDAN/Jordan6_3.png",
      ],
      name: "AIR JORDAN 1 LOW UNC 2021",
      brandName: "JORDAN",
      code: "553558-144",
      price: "5.500.000 VND",
      new: "New",
      discount: "10%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 7,
      mainImg: "./images/JORDAN/Jordan7_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan7_1.png",
        "./images/JORDAN/Jordan7_2.png",
        "./images/JORDAN/Jordan7_3.png",
      ],
      name: "AIR JORDAN 1 MID LIGHT SMOKE GREY ANTHRACITE",
      brandName: "JORDAN",
      code: "554724-078",
      price: "5.900.000 VND",
      discount: "8%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 8,
      mainImg: "./images/JORDAN/Jordan8_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan8_1.png",
        "./images/JORDAN/Jordan8_2.png",
        "./images/JORDAN/Jordan8_3.png",
      ],
      name: "AIR JORDAN 1 MID GS WHITE POLLEN BLACK",
      brandName: "JORDAN",
      code: "554725-177",
      price: "3.900.000 VND",
      new: "New",
      discount: "9%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 9,
      mainImg: "./images/JORDAN/Jordan9_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan9_1.png",
        "./images/JORDAN/Jordan9_2.png",
        "./images/JORDAN/Jordan9_3.png",
      ],
      name: "AIR JORDAN 11 HIGH BRED",
      brandName: "JORDAN",
      code: "378038-061",
      price: "8.500.000 VND",
      new: "New",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 10,
      mainImg: "./images/JORDAN/Jordan10_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan10_1.png",
        "./images/JORDAN/Jordan10_2.png",
        "./images/JORDAN/Jordan10_3.png",
      ],
      name: "AIR JORDAN 5 LOW FIRE RED",
      brandName: "JORDAN",
      code: "314338-101",
      price: "1.500.000 VND",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 11,
      mainImg: "./images/JORDAN/Jordan11_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan11_1.png",
        "./images/JORDAN/Jordan11_2.png",
        "./images/JORDAN/Jordan11_3.png",
      ],
      name: "AIR JORDAN 4 LIGHTNING",
      brandName: "JORDAN",
      code: "CT8527-700",
      price: "6.900.000 VND",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
    {
      id: 12,
      mainImg: "./images/JORDAN/Jordan12_1.png",
      extraImgList: [
        "./images/JORDAN/Jordan12_1.png",
        "./images/JORDAN/Jordan12_2.png",
        "./images/JORDAN/Jordan12_3.png",
      ],
      name: "AIR JORDAN 1 MID PINE GREEN MEN",
      brandName: "JORDAN",
      code: "554724-067",
      price: "4.900.000 VND",
      discount: "20%",
      sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
    },
  ];
  
  export const AdidasData = [
    {
      id: 1,
      mainImg: "./images/ADIDAS/Adidas1_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas1_1.png",
        "./images/ADIDAS/Adidas1_2.png",
        "./images/ADIDAS/Adidas1_3.png",
      ],
      name: "ADIDAS YEEZY 350 V2 BELUGA 2.0",
      brandName: "ADIDAS",
      code: "AH2203",
      price: "9.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 2,
      mainImg: "./images/ADIDAS/Adidas2_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas2_1.png",
        "./images/ADIDAS/Adidas2_2.png",
        "./images/ADIDAS/Adidas2_3.png",
      ],
      name: "ZX 2K BOOST GREY SIGNAL CYAN",
      brandName: "ADIDAS",
      code: "FX8835",
      price: "9.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 3,
      mainImg: "./images/ADIDAS/Adidas3_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas3_1.png",
        "./images/ADIDAS/Adidas3_2.png",
        "./images/ADIDAS/Adidas3_3.png",
      ],
      name: "ADIDAS YEEZY 350 V2 YEEZREEL",
      brandName: "ADIDAS",
      code: "FW5191",
      price: "7.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 4,
      mainImg: "./images/ADIDAS/Adidas4_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas4_1.png",
        "./images/ADIDAS/Adidas4_2.png",
        "./images/ADIDAS/Adidas4_3.png",
      ],
      name: "ADIDAS YEEZY 350 V2 SESAME",
      brandName: "ADIDAS",
      code: "F99710",
      price: "9.000.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 5,
      mainImg: "./images/ADIDAS/Adidas5_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas5_1.png",
        "./images/ADIDAS/Adidas5_2.png",
        "./images/ADIDAS/Adidas5_3.png",
      ],
      name: "ZX 2K BOOST WHITE IRIDESCENT",
      brandName: "ADIDAS",
      code: "FV2928",
      price: "2.290.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 6,
      mainImg: "./images/ADIDAS/Adidas6_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas6_1.png",
        "./images/ADIDAS/Adidas6_2.png",
        "./images/ADIDAS/Adidas6_3.png",
      ],
      name: "YVORI BLUE GREEN RUNNING TRAINERS",
      brandName: "ADIDAS",
      code: "B40908",
      price: "490.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 7,
      mainImg: "./images/ADIDAS/Adidas7_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas7_1.png",
        "./images/ADIDAS/Adidas7_2.png",
        "./images/ADIDAS/Adidas7_3.png",
      ],
      name: "ADIDAS YEEZY 350 V2 CLAY",
      brandName: "ADIDAS",
      code: "EG7490",
      price: "9.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 8,
      mainImg: "./images/ADIDAS/Adidas8_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas8_1.png",
        "./images/ADIDAS/Adidas8_2.png",
        "./images/ADIDAS/Adidas8_3.png",
      ],
      name: "ADIDAS YEEZY 350 V2 GREEN",
      brandName: "ADIDAS",
      code: "BY9611",
      price: "15.000.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 9,
      mainImg: "./images/ADIDAS/Adidas9_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas9_1.png",
        "./images/ADIDAS/Adidas9_2.png",
        "./images/ADIDAS/Adidas9_3.png",
      ],
      name: "NMD R1 Y JAPAN CORE BLACK",
      brandName: "ADIDAS",
      code: "CG6245",
      price: "1.490.000  VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 10,
      mainImg: "./images/ADIDAS/Adidas10_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas10_1.png",
        "./images/ADIDAS/Adidas10_2.png",
        "./images/ADIDAS/Adidas10_3.png",
      ],
      name: "NMD HU PHARRELL X BILLIONAIRE BOYS CLUB MULTI-COLOR ",
      brandName: "ADIDAS",
      code: "BB9544",
      price: "4.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 11,
      mainImg: "./images/ADIDAS/Adidas11_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas11_1.png",
        "./images/ADIDAS/Adidas11_2.png",
        "./images/ADIDAS/Adidas11_3.png",
      ],
      name: "ULTRA BOOST 19 WHI TE BLUE",
      brandName: "ADIDAS",
      code: "EF1340",
      price: "2.200.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 12,
      mainImg: "./images/ADIDAS/Adidas12_1.png",
      extraImgList: [
        "./images/ADIDAS/Adidas12_1.png",
        "./images/ADIDAS/Adidas12_2.png",
        "./images/ADIDAS/Adidas12_3.png",
      ],
      name: "YUNG 1 HI RES ORANGE",
      brandName: "ADIDAS",
      code: "B37613",
      price: "2.190.000 VND",
      new: "New",
      discount: "20%",
    },
  ];
  
  export const MLBData = [
    {
      id: 1,
      mainImg: "./images/MLB/Mlb1_1.png",
      extraImgList: [
        "./images/MLB/Mlb1_1.png",
        "./images/MLB/Mlb1_2.png",
        "./images/MLB/Mlb1_3.png",
      ],
      name: "MLB NY PINK",
      brandName: "MLB",
      code: "MLB-NYP",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 2,
      mainImg: "./images/MLB/Mlb2_1.png",
      extraImgList: [
        "./images/MLB/Mlb2_1.png",
        "./images/MLB/Mlb2_2.png",
        "./images/MLB/Mlb2_3.png",
      ],
      name: "MLB NY BLACK WHITE",
      brandName: "MLB",
      code: "MLB-NYBW",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 3,
      mainImg: "./images/MLB/Mlb3_1.png",
      extraImgList: [
        "./images/MLB/Mlb3_1.png",
        "./images/MLB/Mlb3_2.png",
        "./images/MLB/Mlb3_3.png",
      ],
      name: "MLB NY RED WHITE",
      brandName: "MLB",
      code: "MLB-NYRW",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 4,
      mainImg: "./images/MLB/Mlb4_1.png",
      extraImgList: [
        "./images/MLB/Mlb4_1.png",
        "./images/MLB/Mlb4_2.png",
        "./images/MLB/Mlb4_3.png",
      ],
      name: "MLB BOSTON",
      brandName: "MLB",
      code: "MLB-BT",
      price: "2.900.000 VND",
      new: "New",
      discount: "20%",
    },
  ];
  
  export const PumaData = [
    {
      id: 1,
      mainImg: "./images/PUMA/PUMA1_1.png",
      extraImgList: [
        "./images/PUMA/Puma1_1.png",
        "./images/PUMA/Puma1_2.png",
        "./images/PUMA/Puma1_3.png",
      ],
      name: "PUMA SUEDE BLUE",
      brandName: "PUMA",
      code: "362223-02",
      price: "2.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 2,
      mainImg: "./images/PUMA/Puma2_1.png",
      extraImgList: [
        "./images/PUMA/Puma2_1.png",
        "./images/PUMA/Puma_2.png",
        "./images/PUMA/Puma2_3.png",
      ],
      name: "PUMA THUNDER SPECTRA",
      brandName: "PUMA",
      code: "367516-02",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 3,
      mainImg: "./images/PUMA/Puma3_1.png",
      extraImgList: [
        "./images/PUMA/Puma3_1.png",
        "./images/PUMA/Puma3_2.png",
        "./images/PUMA/Puma3_3.png",
      ],
      name: "PUMA THUNDER 4 LIFE",
      brandName: "PUMA",
      code: "367516-02",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 4,
      mainImg: "./images/PUMA/Puma4_1.png",
      extraImgList: [
        "./images/PUMA/Puma4_1.png",
        "./images/PUMA/Puma4_2.png",
        "./images/PUMA/Puma4_3.png",
      ],
      name: "PUMA RS-X RETRO RED GREY INDIGO",
      brandName: "PUMA",
      code: "371511-01",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
  
    {
      id: 5,
      mainImg: "./images/PUMA/Puma5_1.png",
      extraImgList: [
        "./images/PUMA/Puma5_1.png",
        "./images/PUMA/Puma5_2.png",
        "./images/PUMA/Puma5_3.png",
      ],
      name: "PUMA RSX TRACKS JR",
      brandName: "PUMA",
      code: "369629-02",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 6,
      mainImg: "./images/PUMA/Puma6_1.png",
      extraImgList: [
        "./images/PUMA/Puma6_1.png",
        "./images/PUMA/Puma6_2.png",
        "./images/PUMA/Puma6_3.png",
      ],
      name: "PUMA RSX WHISPER WHITE",
      brandName: "PUMA",
      code: "369329-03",
      price: "3.500.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 7,
      mainImg: "./images/PUMA/Puma7_1.png",
      extraImgList: [
        "./images/PUMA/Puma7_1.png",
        "./images/PUMA/Puma7_2.png",
        "./images/PUMA/Puma7_3.png",
      ],
      name: "PUMA RSX HARD DRIVE",
      brandName: "PUMA",
      code: "370644-03",
      price: "3.300.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 8,
      mainImg: "./images/PUMA/Puma8_1.png",
      extraImgList: [
        "./images/PUMA/Puma8_1.png",
        "./images/PUMA/Puma8_2.png",
        "./images/PUMA/Puma8_3.png",
      ],
      name: "PUMA RS-X REINVENTION",
      brandName: "PUMA",
      code: "369579-02",
      price: "3.600.000 VND",
      new: "New",
      discount: "20%",
    },
    {
      id: 9,
      mainImg: "./images/PUMA/Puma9_1.png",
      extraImgList: [
        "./images/PUMA/Puma9_1.png",
        "./images/PUMA/Puma9_2.png",
        "./images/PUMA/Puma9_3.png",
      ],
      name: "PUMA RS-X TOYS",
      brandName: "PUMA",
      code: "369628-02",
      price: "3.600.000 VND",
      new: "New",
      discount: "20%",
    },
  ];
  